import type { ProductItem, SectionBanner } from '@/types/product';

export const EQUIPMENT_BANNER: SectionBanner = {
  title: 'Smart tools\neasier farming',
  subtitle: 'Reliable equipment for spraying, digging, and daily field care.',
  image: require('../../assets/images/categories/smarttoolsbanner.png'),
};

export const EQUIPMENT_PRODUCTS: ProductItem[] = [
  {
    id: 'eq-1',
    name: 'siddhi inline drip 1000m - d...',
    specs: '16mm, 4ltr, 50cm',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/siddhirope.png'),
    category: 'equipments',
  },
  {
    id: 'eq-2',
    name: 'tapas pehelwaan 101',
    specs: '1L',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/sprayer.png'),
    category: 'equipments',
  },
  {
    id: 'eq-3',
    name: 'Backpack Sprayer',
    specs: '16L manual sprayer',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/backpacksprayer.png'),
    category: 'equipments',
  },
  {
    id: 'eq-4',
    name: 'Seed Drill Machine',
    specs: 'Tractor mounted, 11 row',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/seeddrillmachine.png'),
    category: 'equipments',
  },
  {
    id: 'eq-5',
    name: 'Farm Tractor',
    specs: '45 HP, 4WD tractor',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/farmtractor.png'),
    category: 'equipments',
  },
  {
    id: 'eq-6',
    name: 'Power Tiller',
    specs: '7HP petrol engine',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/powertiller.png'),
    category: 'equipments',
  },
  {
    id: 'eq-7',
    name: 'Self-Propelled Boom Sprayer',
    specs: '600m Sprayer',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/boomsprayer.png'),
    category: 'equipments',
  },
  {
    id: 'eq-8',
    name: 'Rice Transplanter',
    specs: '4-row, paddy transplanter',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/ricetransplanter.png'),
    category: 'equipments',
  },
  {
    id: 'eq-9',
    name: 'Rotary Tiller',
    specs: 'Heavy duty, 42 blades',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/rotarytiller.png'),
    category: 'equipments',
  },
  {
    id: 'eq-10',
    name: 'Combine Harvester',
    specs: 'Multi-crop harvester',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/combineharvester.png'),
    category: 'equipments',
  },
];
