import type { ProductItem, SectionBanner } from '@/types/product';

export const FERTILIZER_BANNER: SectionBanner = {
  title: 'Better fertilizer\nhealthier growth',
  subtitle: 'Balanced nutrition for greener leaves and stronger roots.',
  image: require('../../assets/images/categories/fertilizerbanner.png'),
};

export const FERTILIZER_PRODUCTS: ProductItem[] = [
  {
    id: 'fert-1',
    name: 'Compo Expert Zitrilon 15 W...',
    specs: '500g',
    pricePaise: 110000,
    originalPricePaise: 200000,
    discountPercentage: 45,
    image: require('../../assets/images/categories/compoexpertzitrilon.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-2',
    name: 'Agriventure Kheti Uday (A...',
    specs: '500g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/agriventurekhetiuday.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-3',
    name: 'GreenField Nutrition-NPK...',
    specs: '1kg',
    pricePaise: 110000,
    originalPricePaise: 200000,
    discountPercentage: 45,
    image: require('../../assets/images/categories/greenfieldnutrition-npk.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-4',
    name: 'GreenNourish Fertilizer NPK...',
    specs: '1kg',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/greennourishfertilizer-npk.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-5',
    name: 'GreenHarvest-Liquid Fertili...',
    specs: '1L',
    pricePaise: 110000,
    originalPricePaise: 200000,
    discountPercentage: 45,
    image: require('../../assets/images/categories/greenharvest-liquid fertilizer.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-6',
    name: 'GreenHarv-Fertilizer NPK...',
    specs: '1kg',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/greenharv-fertilizer-npk.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-7',
    name: 'GreenField-Nutrition NPK...',
    specs: '1kg',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/greenfiel-nutrition-npk.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-8',
    name: 'GreenNourish-Fertilizer NPK...',
    specs: '1kg',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/greennourish-npk.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-9',
    name: 'GreenNourish-Fertilizer NPK...',
    specs: '1kg',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/greennourishfertilizer-npk.png'),
    category: 'fertilizers',
  },
  {
    id: 'fert-10',
    name: 'GreenNourish-Fertilizer NPK...',
    specs: '1kg',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/greennourish-npk.png'),
    category: 'fertilizers',
  },
];
