import type { ProductItem, SectionBanner } from '@/types/product';

export const PESTICIDE_BANNER: SectionBanner = {
  title: 'Protect crops\nstop damage',
  subtitle: 'Effective care solutions for healthier plants and better harvests.',
  image: require('../../assets/images/categories/pesticidebanner.png'),
};

export const PESTICIDE_PRODUCTS: ProductItem[] = [
  {
    id: 'pest-1',
    name: 'UPL Saaf Fungicide',
    specs: '250g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/uplsaaf.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-2',
    name: 'Bayer Nativo Fungicide',
    specs: '250g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/bayernatner.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-3',
    name: 'Beta - Bio and Eco-Friendly...',
    specs: '1000ml',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/beta-bio.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-4',
    name: 'Texan PW Insecticide...',
    specs: '500ml',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/texanpw.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-5',
    name: 'AgroShield-CopperMax...',
    specs: '250g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/agroshield-coppermix.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-6',
    name: 'CropGuard NativoPlus ...',
    specs: '100g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/cropguard-nativoplus.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-7',
    name: 'FieldMaster-WeedOut...',
    specs: '250g',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/fieldmaster-weedout.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-8',
    name: 'AgriNova-RootPlus Plant ...',
    specs: '1L',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/agrinova-rootplus.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-9',
    name: 'AgroVita-PestNil Insecticide',
    specs: '500ml',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/agrovita-pestnil.png'),
    category: 'pesticides',
  },
  {
    id: 'pest-10',
    name: 'FarmCure-Texon PW...',
    specs: '500ml',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/farmcure-texon.png'),
    category: 'pesticides',
  },
];
