import type { ProductItem, SectionBanner } from '@/types/product';

export const SEEDS_BANNER: SectionBanner = {
  title: 'Organic care\nstronger plants',
  subtitle: 'Natural solutions that support growth, vitality, and yield.',
  image: require('../../assets/images/categories/seedsbanner.png'),
};

export const SEEDS_PRODUCTS: ProductItem[] = [
  {
    id: 'seed-1',
    name: 'Shriram Bioseed 6001 Cott...',
    specs: '250g',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/shriram-bioseed-cotton.png'),
    category: 'seeds',
  },
  {
    id: 'seed-2',
    name: 'Sri Rama Punch Cotton Se...',
    specs: '250g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/sriram-punch.png'),
    category: 'seeds',
  },
  {
    id: 'seed-3',
    name: 'UPL Golden Paddy Seeds',
    specs: '250g',
    pricePaise: 110000,
    originalPricePaise: 132000,
    discountPercentage: 14,
    image: require('../../assets/images/categories/upl-goldenseeds.png'),
    category: 'seeds',
  },
  {
    id: 'seed-4',
    name: 'Syngenta Hybrid Tomato',
    specs: '250g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/syngenta-hybrid-tomato.png'),
    category: 'seeds',
  },
  {
    id: 'seed-5',
    name: 'Shriram Bioseed 6001 Cott...',
    specs: '250g',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/shriram-bioseed-cotton.png'),
    category: 'seeds',
  },
  {
    id: 'seed-6',
    name: 'Sri Rama Punch Cotton Se...',
    specs: '250g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/sriram-punch.png'),
    category: 'seeds',
  },
  {
    id: 'seed-7',
    name: 'Agrovista Hybrid Chilli...',
    specs: '1kg',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/agrovista-chilli.png'),
    category: 'seeds',
  },
  {
    id: 'seed-8',
    name: 'Agrovista Hybrid Maize Seeds',
    specs: '1kg',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/agrovista-maize.png'),
    category: 'seeds',
  },
  {
    id: 'seed-9',
    name: 'Premium Purple Snow Peas',
    specs: '500g',
    pricePaise: 100078,
    originalPricePaise: 116400,
    discountPercentage: 14,
    image: require('../../assets/images/categories/purple-snowpeas.png'),
    category: 'seeds',
  },
  {
    id: 'seed-10',
    name: 'Premium Bell Pepper Se...',
    specs: '250g',
    pricePaise: 46665,
    originalPricePaise: 54600,
    discountPercentage: 14,
    image: require('../../assets/images/categories/bellpepper-seeds.png'),
    category: 'seeds',
  },
];
